# Generated by Django 3.0 on 2019-12-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployedapp',
            old_name='app_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='deployedapp',
            name='server',
        ),
        migrations.AddField(
            model_name='deployedapp',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployedapp',
            name='icon',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployedapp',
            name='ip',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployedapp',
            name='port',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
