# Generated by Django 3.0 on 2019-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20191216_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedapp',
            name='port',
            field=models.CharField(max_length=255),
        ),
    ]
